services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: records
    volumes:
      - records-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=records"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: floriaaan/records:latest-linux-amd64
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/records
      - TEST_DATABASE_URL=postgres://user:password@test_db:5432/test_records
      - ROCKET_DATABASES={records={url=postgres://user:password@db:5432/records}}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check"]
      interval: 1h
      timeout: 5s
      retries: 5

volumes:
  records-db-data:
  test-records-db-data:
