[default]
address = "0.0.0.0"
port = 8000
workers = 16
max_blocking = 512
keep_alive = 5
ident = "floriaaan_records"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true

[default.databases.records]
url = "postgres://user:password@localhost/records"
min_connections = 1
max_connections = 5
connect_timeout = 5
idle_timeout = 120