###
# @prompt username Your username
# @prompt email Your email
# @prompt password Your password

POST http://localhost:8000/auth/register
content-type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "password_confirmation": "{{password}}"
}