name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on any tag push
  pull_request:

jobs:
  build-linux:
    name: Build & Push Docker (Linux x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Git Tag as Docker Tag
        id: git_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}  # Remove refs/tags/ prefix
            echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          else
            echo "No tag found, defaulting to 'latest'"
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi

      - name: Build & Push Linux Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: TARGET=x86_64-unknown-linux-gnu
          platforms: linux/amd64
          push: true
          tags: |
            floriaaan/records:${{ env.TAG_NAME }}
            floriaaan/records:latest

  # build-macos:
  #   name: Build & Push Docker (Mac arm64)
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup Docker on macOS
  #       uses: douglascamata/setup-docker-macos-action@v1-alpha

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build & Push macOS Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: Dockerfile
  #         build-args: TARGET=aarch64-apple-darwin
  #         platforms: darwin/arm64
  #         push: true
  #         tags: |
  #           floriaaan/records:latest-darwin-arm64
  #           floriaaan/records:${{ github.sha }}-darwin-arm64
